[workspace]
members = ["kernel", "user"]
exclude = ["bootloader"]
default-members = ["kernel"]
resolver = "3"

[profile.release]
# panic = "abort"
opt-level = "s"
lto = "fat"

[profile.dev]
# panic = "abort"
opt-level = "s"
