[workspace]
members = ["kernel", "user"]
exclude = ["bootloader"]
default-members = ["kernel"]
resolver = "3"

[profile.release]
panic = "abort"
opt-level = "s"
lto = "fat"
debug = true  # 保留调试符号

[profile.dev]
panic = "abort"
opt-level = "s"
debug = true  # 保留调试符号
debug-assertions = true
