use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use proc_macro2::Span;
use quote::ToTokens;
use syn::{
    Arm, Expr, ExprLit, ExprMatch, ExprRange, Field, File, ForeignItemFn, ImplItemFn, ItemConst,
    ItemEnum, ItemFn, ItemForeignMod, ItemImpl, ItemMod, ItemStatic, ItemStruct, ItemTrait,
    ItemType, ItemUnion, ItemUse, Lit, Macro, Pat, PatIdent, Path as SynPath, Signature, TraitItem,
    UseTree, Visibility, spanned::Spanned, visit::Visit,
};

const INTERFACE_HEADER: &str = "# Generated by cargo run -p architecture-check -- --write-interface\n\
# Any change is an architecture interface change and must be reviewed.\n";

const DEFAULT_SOURCE_LINE_LIMIT: usize = 600;
const ABSOLUTE_SOURCE_LINE_LIMIT: usize = 2_500;

const KERNEL_MODULES: &[&str] = &[
    "arch",
    "config",
    "drivers",
    "fs",
    "id",
    "ipc",
    "lang_item",
    "log",
    "main",
    "memory",
    "random",
    "socket",
    "sync",
    "syscall",
    "system",
    "task",
    "timer",
    "trap",
];

#[derive(Clone, Copy)]
struct SourceDomain {
    root: &'static str,
    binary_crate: bool,
}

const SOURCE_DOMAINS: &[SourceDomain] = &[
    SourceDomain {
        root: "kernel/src",
        binary_crate: true,
    },
    SourceDomain {
        root: "bootloader/src",
        binary_crate: true,
    },
];

struct SourceFile {
    relative: String,
    owner: String,
    text: String,
    lines: Vec<String>,
    syntax: File,
    binary_crate: bool,
}

impl SourceFile {
    fn at(&self, line: usize) -> String {
        format!("{}:{line}", self.relative)
    }

    fn preceding_contains(&self, line: usize, distance: usize, marker: &str) -> bool {
        let start = line.saturating_sub(distance + 1);
        self.lines[start..line.saturating_sub(1).min(self.lines.len())]
            .iter()
            .any(|candidate| candidate.contains(marker))
    }
}

fn main() -> ExitCode {
    let write_interface = env::args().skip(1).any(|arg| arg == "--write-interface");
    let root = repository_root();
    let mut errors = Vec::new();
    let sources = match load_sources(&root) {
        Ok(sources) => sources,
        Err(error) => {
            eprintln!("architecture fence failed:\n- {error}");
            return ExitCode::FAILURE;
        }
    };

    check_dependencies(&root, &sources, &mut errors);
    check_source_sizes(&root, &sources, &mut errors);
    check_visibility(&sources, &mut errors);
    check_source_patterns(&root, &sources, &mut errors);
    check_global_owners(&sources, &mut errors);
    check_unsafe_proofs(&sources, &mut errors);
    check_abi(&root, &mut errors);
    check_documentation(&root, &mut errors);
    check_userspace_single_track(&root, &mut errors);

    let surface = interface_surface(&sources);
    if write_interface {
        if errors.is_empty() {
            let baseline = root.join("docs/architecture-interface.txt");
            let content = format!("{INTERFACE_HEADER}{}\n", surface.join("\n"));
            if let Err(error) = fs::write(&baseline, content) {
                errors.push(format!("failed to write {}: {error}", baseline.display()));
            }
        }
    } else {
        check_interface_baseline(&root, &surface, &mut errors);
    }

    if errors.is_empty() {
        println!("architecture fence passed");
        ExitCode::SUCCESS
    } else {
        eprintln!("architecture fence failed:");
        for error in errors {
            eprintln!("- {error}");
        }
        ExitCode::FAILURE
    }
}

fn repository_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("architecture-check must live under tools/")
        .to_path_buf()
}

struct SourceSizeException {
    limit: usize,
    owner: String,
    reason: String,
    exit: String,
}

fn source_size_exceptions(root: &Path) -> Result<BTreeMap<String, SourceSizeException>, String> {
    let path = root.join("docs/architecture-contract.md");
    let text = fs::read_to_string(&path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let mut exceptions = BTreeMap::new();
    for line in text.lines() {
        let columns: Vec<&str> = line.split('|').map(str::trim).collect();
        if columns.len() < 7 || !columns[1].starts_with('`') {
            continue;
        }
        let relative = columns[1].trim_matches('`');
        if !relative.starts_with("kernel/src/") && !relative.starts_with("bootloader/src/") {
            continue;
        }
        let Ok(limit) = columns[2].parse::<usize>() else {
            continue;
        };
        let exception = SourceSizeException {
            limit,
            owner: columns[3].trim_matches('`').to_owned(),
            reason: columns[4].to_owned(),
            exit: columns[5].to_owned(),
        };
        if exception.limit <= DEFAULT_SOURCE_LINE_LIMIT {
            return Err(format!(
                "{relative}: size exception must exceed the default {DEFAULT_SOURCE_LINE_LIMIT}-line limit"
            ));
        }
        if exception.limit > ABSOLUTE_SOURCE_LINE_LIMIT {
            return Err(format!(
                "{relative}: size exception exceeds the absolute {ABSOLUTE_SOURCE_LINE_LIMIT}-line limit"
            ));
        }
        if exception.owner.is_empty() || exception.reason.is_empty() || exception.exit.is_empty() {
            return Err(format!(
                "{relative}: size exception requires owner, reason and exit criterion"
            ));
        }
        if exceptions.insert(relative.to_owned(), exception).is_some() {
            return Err(format!("duplicate source-size exception for {relative}"));
        }
    }
    Ok(exceptions)
}

fn check_source_sizes(root: &Path, sources: &[SourceFile], errors: &mut Vec<String>) {
    let exceptions = match source_size_exceptions(root) {
        Ok(exceptions) => exceptions,
        Err(error) => {
            errors.push(error);
            return;
        }
    };
    let known: BTreeSet<&str> = sources
        .iter()
        .map(|source| source.relative.as_str())
        .collect();
    for relative in exceptions.keys() {
        if !known.contains(relative.as_str()) {
            errors.push(format!(
                "{relative}: source-size exception does not name a production Rust source"
            ));
        }
    }
    for source in sources {
        let lines = source.lines.len();
        if lines > ABSOLUTE_SOURCE_LINE_LIMIT {
            errors.push(format!(
                "{}: {lines} lines exceeds the absolute source-file limit {ABSOLUTE_SOURCE_LINE_LIMIT}",
                source.relative
            ));
            continue;
        }
        let exception = exceptions.get(&source.relative);
        if let Some(exception) = exception
            && exception.owner != source.owner
            && !exception.owner.starts_with(&format!("{}::", source.owner))
        {
            errors.push(format!(
                "{}: size exception owner `{}` does not belong to module `{}`",
                source.relative, exception.owner, source.owner
            ));
        }
        let limit = exception.map_or(DEFAULT_SOURCE_LINE_LIMIT, |exception| exception.limit);
        if lines > limit {
            errors.push(format!(
                "{}: {lines} lines exceeds its architecture source-file limit {limit}",
                source.relative
            ));
        } else if exception.is_some() && lines < limit {
            errors.push(format!(
                "{}: source shrank to {lines} lines; lower its architecture limit from {limit} to preserve the ratchet",
                source.relative
            ));
        }
    }
}

fn check_userspace_single_track(root: &Path, errors: &mut Vec<String>) {
    let allowed_user_files = BTreeSet::from([
        "busybox.config",
        "dynamic-smoke-lib.c",
        "dynamic-smoke.c",
        "group",
        "inittab",
        "musl-smoke.c",
        "network-service",
        "passwd",
        "udhcpc.script",
    ]);
    match fs::read_dir(root.join("user")) {
        Ok(entries) => {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().into_owned();
                if !allowed_user_files.contains(name.as_str()) {
                    errors.push(format!(
                        "user/{name}: only fixed BusyBox identity/init/network policy and musl/dynamic-loader consumers are allowed"
                    ));
                }
            }
        }
        Err(error) => errors.push(format!("failed to inspect user/: {error}")),
    }
    for relative in ["user/Cargo.toml", "user/src", "user/linker.ld"] {
        if root.join(relative).exists() {
            errors.push(format!(
                "{relative}: Rust userspace track is forbidden; BusyBox is the unique product rootfs"
            ));
        }
    }
    let manifest = fs::read_to_string(root.join("Cargo.toml")).unwrap_or_default();
    if manifest
        .lines()
        .any(|line| line.starts_with("members") && line.split('"').any(|member| member == "user"))
    {
        errors.push("Cargo.toml: user crate must not re-enter the workspace".to_owned());
    }
    let makefile = fs::read_to_string(root.join("Makefile")).unwrap_or_default();
    for forbidden in ["build-user", "release/init", "create-fs"] {
        if makefile.contains(forbidden) {
            errors.push(format!(
                "Makefile: legacy userspace path `{forbidden}` is forbidden"
            ));
        }
    }
    let required = "python3 scripts/verify_busybox.py --build-only --image fs.img";
    if !makefile.contains(required) {
        errors.push(format!(
            "Makefile: default rootfs must be built through `{required}`"
        ));
    }
}

fn rust_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("failed to read {}: {error}", directory.display()))?;
    for entry in entries {
        let path = entry
            .map_err(|error| format!("failed to read directory entry: {error}"))?
            .path();
        if path.is_dir() {
            rust_files(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            files.push(path);
        }
    }
    Ok(())
}

fn load_sources(root: &Path) -> Result<Vec<SourceFile>, String> {
    let mut sources = Vec::new();
    for domain in SOURCE_DOMAINS {
        let source_root = root.join(domain.root);
        let mut paths = Vec::new();
        rust_files(&source_root, &mut paths)?;
        paths.sort();
        for path in paths {
            let text = fs::read_to_string(&path)
                .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
            let syntax = syn::parse_file(&text)
                .map_err(|error| format!("failed to parse {}: {error}", path.display()))?;
            let relative_path = path
                .strip_prefix(root)
                .map_err(|error| format!("invalid source path {}: {error}", path.display()))?;
            let owner = module_owner(relative_path, domain.root);
            sources.push(SourceFile {
                relative: relative_path.to_string_lossy().replace('\\', "/"),
                owner,
                lines: text.lines().map(str::to_owned).collect(),
                text,
                syntax,
                binary_crate: domain.binary_crate,
            });
        }
    }
    Ok(sources)
}

fn module_owner(relative: &Path, source_root: &str) -> String {
    let inside = relative
        .strip_prefix(source_root)
        .expect("source path must be below its source root");
    let first = inside
        .components()
        .next()
        .expect("Rust source path is not empty");
    let name = first.as_os_str().to_string_lossy();
    name.strip_suffix(".rs").unwrap_or(&name).to_owned()
}

#[derive(Default)]
struct PathCollector {
    paths: Vec<Vec<String>>,
    crate_root_alias: bool,
}

impl<'ast> Visit<'ast> for PathCollector {
    fn visit_path(&mut self, path: &'ast SynPath) {
        self.paths.push(
            path.segments
                .iter()
                .map(|segment| segment.ident.to_string())
                .collect(),
        );
        syn::visit::visit_path(self, path);
    }

    fn visit_item_use(&mut self, item: &'ast ItemUse) {
        self.crate_root_alias |= aliases_crate_root(&item.tree);
        expand_use_tree(Vec::new(), &item.tree, &mut self.paths);
    }
}

fn aliases_crate_root(tree: &UseTree) -> bool {
    match tree {
        UseTree::Rename(rename) => rename.ident == "crate",
        UseTree::Name(name) => name.ident == "crate",
        UseTree::Path(path) if path.ident == "crate" => matches!(*path.tree, UseTree::Glob(_)),
        _ => false,
    }
}

fn expand_use_tree(prefix: Vec<String>, tree: &UseTree, paths: &mut Vec<Vec<String>>) {
    match tree {
        UseTree::Path(path) => {
            let mut next = prefix;
            next.push(path.ident.to_string());
            expand_use_tree(next, &path.tree, paths);
        }
        UseTree::Name(name) => {
            let mut path = prefix;
            path.push(name.ident.to_string());
            paths.push(path);
        }
        UseTree::Rename(rename) => {
            let mut path = prefix;
            path.push(rename.ident.to_string());
            paths.push(path);
        }
        UseTree::Glob(_) => paths.push(prefix),
        UseTree::Group(group) => {
            for item in &group.items {
                expand_use_tree(prefix.clone(), item, paths);
            }
        }
    }
}

fn allowed_dependencies(root: &Path) -> Result<BTreeMap<String, BTreeSet<String>>, String> {
    let path = root.join("docs/architecture-contract.md");
    let text = fs::read_to_string(&path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let mut rules = BTreeMap::new();
    for line in text.lines() {
        let columns: Vec<&str> = line.split('|').map(str::trim).collect();
        if columns.len() < 5 || !columns[1].starts_with('`') {
            continue;
        }
        let owner = columns[1].trim_matches('`');
        if !KERNEL_MODULES.contains(&owner) {
            continue;
        }
        let mut allowed = BTreeSet::new();
        let mut remainder = columns[2];
        while let Some(start) = remainder.find('`') {
            remainder = &remainder[start + 1..];
            let Some(end) = remainder.find('`') else {
                return Err(format!("{owner}: malformed dependency matrix row"));
            };
            let dependency = &remainder[..end];
            if !KERNEL_MODULES.contains(&dependency) {
                return Err(format!(
                    "{owner}: dependency matrix names unknown module `{dependency}`"
                ));
            }
            allowed.insert(dependency.to_owned());
            remainder = &remainder[end + 1..];
        }
        if rules.insert(owner.to_owned(), allowed).is_some() {
            return Err(format!(
                "docs/architecture-contract.md contains duplicate dependency rows for `{owner}`"
            ));
        }
    }
    for module in KERNEL_MODULES {
        if !rules.contains_key(*module) {
            return Err(format!(
                "docs/architecture-contract.md lacks a dependency row for `{module}`"
            ));
        }
    }
    Ok(rules)
}

fn check_dependencies(root: &Path, sources: &[SourceFile], errors: &mut Vec<String>) {
    let allowlist = match allowed_dependencies(root) {
        Ok(allowlist) => allowlist,
        Err(error) => {
            errors.push(error);
            return;
        }
    };
    let known: BTreeSet<&str> = KERNEL_MODULES.iter().copied().collect();
    for source in sources
        .iter()
        .filter(|source| source.relative.starts_with("kernel/src/"))
    {
        let mut collector = PathCollector::default();
        collector.visit_file(&source.syntax);
        if collector.crate_root_alias {
            errors.push(format!(
                "{}: aliasing or glob-importing the crate root bypasses dependency ownership",
                source.relative
            ));
        }
        let mut dependencies = BTreeSet::new();
        for path in &collector.paths {
            if path.first().is_some_and(|segment| segment == "crate")
                && let Some(module) = path.get(1)
                && known.contains(module.as_str())
                && module != &source.owner
            {
                dependencies.insert(module.as_str());
            }
            check_facade_path(source, path, errors);
        }
        let Some(allowed) = allowlist.get(source.owner.as_str()) else {
            errors.push(format!(
                "{}: kernel module `{}` has no positive dependency contract",
                source.relative, source.owner
            ));
            continue;
        };
        for dependency in dependencies {
            if allowed.contains(dependency) {
                continue;
            }
            errors.push(format!(
                "{}: crate::{} is absent from the positive dependency contract for {}",
                source.relative, dependency, source.owner
            ));
        }
    }

    for source in sources
        .iter()
        .filter(|source| source.relative.starts_with("bootloader/src/"))
    {
        if source.text.contains("kernel::") || source.text.contains("user::") {
            errors.push(format!(
                "{}: bootloader must remain an independent M-mode domain",
                source.relative
            ));
        }
    }
}

fn check_facade_path(source: &SourceFile, path: &[String], errors: &mut Vec<String>) {
    if path.first().is_none_or(|segment| segment != "crate") {
        return;
    }
    if source.owner == "fs"
        && path.get(1).is_some_and(|segment| segment == "drivers")
        && path.get(2).is_none_or(|segment| segment != "block")
    {
        errors.push(format!(
            "{}: filesystem may depend only on the drivers::block seam",
            source.relative
        ));
    }
    if source.owner == "syscall" {
        if matches!(
            path.get(1).map(String::as_str),
            Some("fs" | "memory" | "task")
        ) && path.len() == 2
        {
            errors.push(format!(
                "{}: syscall must import a named domain facade item, not alias its module root",
                source.relative
            ));
        }
        let forbidden = [
            &["crate", "fs", "ext2"][..],
            &["crate", "fs", "file"][..],
            &["crate", "fs", "inode"][..],
            &["crate", "fs", "Ext2FileSystem"][..],
            &["crate", "memory", "page_table"][..],
            &["crate", "task", "scheduler"][..],
        ];
        if forbidden.iter().any(|prefix| {
            path.len() >= prefix.len()
                && path
                    .iter()
                    .map(String::as_str)
                    .zip(prefix.iter().copied())
                    .all(|(actual, expected)| actual == expected)
        }) {
            errors.push(format!(
                "{}: syscall bypasses a domain facade through {}",
                source.relative,
                path.join("::")
            ));
        }
    }
    if source.owner == "task"
        && path.get(1).is_some_and(|segment| segment == "fs")
        && path
            .get(2)
            .is_some_and(|segment| segment == "Ext2FileSystem")
    {
        errors.push(format!(
            "{}: task may consume filesystem interfaces but not the ext2 adapter",
            source.relative
        ));
    }
}

fn is_scoped_visible(visibility: &Visibility) -> bool {
    matches!(visibility, Visibility::Restricted(restricted) if !restricted.path.is_ident("self"))
}

fn is_bare_public(visibility: &Visibility) -> bool {
    matches!(visibility, Visibility::Public(_))
}

fn normalized(tokens: impl ToTokens) -> String {
    tokens.into_token_stream().to_string()
}

struct SurfaceCollector<'a> {
    relative: &'a str,
    entries: Vec<String>,
    errors: Option<&'a mut Vec<String>>,
    binary_crate: bool,
    owner: Vec<String>,
}

impl SurfaceCollector<'_> {
    fn record(&mut self, declaration: String) {
        self.entries
            .push(format!("{} :: {}", self.relative, declaration.trim()));
    }

    fn visibility(&mut self, visibility: &Visibility, span: Span, declaration: String) -> bool {
        if self.binary_crate
            && is_bare_public(visibility)
            && let Some(errors) = self.errors.as_deref_mut()
        {
            errors.push(format!(
                "{}:{}: binary-crate implementation must use scoped visibility",
                self.relative,
                span.start().line
            ));
        }
        if is_scoped_visible(visibility) {
            self.record(format!("{} {declaration}", normalized(visibility)));
            true
        } else {
            false
        }
    }

    fn owner_name(&self) -> String {
        self.owner.join("::")
    }

    fn signature(&mut self, visibility: &Visibility, signature: &Signature, span: Span) {
        let owner = self.owner_name();
        let signature = normalized(signature);
        let declaration = if owner.is_empty() {
            signature
        } else {
            format!("impl {owner} :: {signature}")
        };
        self.visibility(visibility, span, declaration);
    }
}

impl<'ast> Visit<'ast> for SurfaceCollector<'_> {
    fn visit_item_fn(&mut self, item: &'ast ItemFn) {
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }

    fn visit_item_struct(&mut self, item: &'ast ItemStruct) {
        let name = item.ident.to_string();
        let declaration = format!("struct {} {}", item.ident, normalized(&item.generics));
        self.visibility(&item.vis, item.ident.span(), declaration);
        self.owner.push(name);
        for field in &item.fields {
            self.visit_field(field);
        }
        self.owner.pop();
    }

    fn visit_item_union(&mut self, item: &'ast ItemUnion) {
        let declaration = format!("union {}", item.ident);
        self.visibility(&item.vis, item.ident.span(), declaration);
        self.owner.push(item.ident.to_string());
        for field in &item.fields.named {
            self.visit_field(field);
        }
        self.owner.pop();
    }

    fn visit_field(&mut self, field: &'ast Field) {
        let name = field
            .ident
            .as_ref()
            .map_or_else(|| "<tuple>".to_owned(), ToString::to_string);
        let owner = self.owner_name();
        let ty = normalized(&field.ty);
        self.visibility(
            &field.vis,
            field
                .ident
                .as_ref()
                .map_or_else(Span::call_site, |id| id.span()),
            format!("{owner} :: {name} : {ty}"),
        );
    }

    fn visit_item_enum(&mut self, item: &'ast ItemEnum) {
        if self.visibility(
            &item.vis,
            item.ident.span(),
            format!("enum {} {}", item.ident, normalized(&item.generics)),
        ) {
            for variant in &item.variants {
                self.record(format!("enum {} :: {}", item.ident, normalized(variant)));
            }
        }
    }

    fn visit_item_trait(&mut self, item: &'ast ItemTrait) {
        if self.visibility(
            &item.vis,
            item.ident.span(),
            format!("trait {} {}", item.ident, normalized(&item.generics)),
        ) {
            for trait_item in &item.items {
                let declaration = match trait_item {
                    TraitItem::Fn(function) => normalized(&function.sig),
                    TraitItem::Const(constant) => {
                        format!("const {} : {}", constant.ident, normalized(&constant.ty))
                    }
                    TraitItem::Type(ty) => {
                        format!("type {} {}", ty.ident, normalized(&ty.generics))
                    }
                    other => normalized(other),
                };
                self.record(format!("trait {} :: {declaration}", item.ident));
            }
        }
    }

    fn visit_item_impl(&mut self, item: &'ast ItemImpl) {
        self.owner.push(normalized(&item.self_ty));
        syn::visit::visit_item_impl(self, item);
        self.owner.pop();
    }

    fn visit_impl_item_fn(&mut self, item: &'ast ImplItemFn) {
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }

    fn visit_item_const(&mut self, item: &'ast ItemConst) {
        let declaration = format!(
            "const {} : {} = {}",
            item.ident,
            normalized(&item.ty),
            normalized(&item.expr)
        );
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_static(&mut self, item: &'ast ItemStatic) {
        let declaration = format!("static {} : {}", item.ident, normalized(&item.ty));
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_type(&mut self, item: &'ast ItemType) {
        let declaration = format!(
            "type {} {} = {}",
            item.ident,
            normalized(&item.generics),
            normalized(&item.ty)
        );
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_mod(&mut self, item: &'ast ItemMod) {
        self.visibility(&item.vis, item.ident.span(), format!("mod {}", item.ident));
        syn::visit::visit_item_mod(self, item);
    }

    fn visit_item_use(&mut self, item: &'ast ItemUse) {
        self.visibility(
            &item.vis,
            item.use_token.span,
            format!("use {}", normalized(&item.tree)),
        );
    }

    fn visit_foreign_item_fn(&mut self, item: &'ast ForeignItemFn) {
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }
}

fn interface_surface(sources: &[SourceFile]) -> Vec<String> {
    let mut surface = Vec::new();
    for source in sources.iter().filter(|source| source.binary_crate) {
        let mut collector = SurfaceCollector {
            relative: &source.relative,
            entries: Vec::new(),
            errors: None,
            binary_crate: source.binary_crate,
            owner: Vec::new(),
        };
        collector.visit_file(&source.syntax);
        surface.extend(collector.entries);
    }
    surface.sort();
    surface.dedup();
    surface
}

fn check_visibility(sources: &[SourceFile], errors: &mut Vec<String>) {
    for source in sources.iter().filter(|source| source.binary_crate) {
        let mut collector = SurfaceCollector {
            relative: &source.relative,
            entries: Vec::new(),
            errors: Some(errors),
            binary_crate: source.binary_crate,
            owner: Vec::new(),
        };
        collector.visit_file(&source.syntax);
    }
}

fn check_interface_baseline(root: &Path, current: &[String], errors: &mut Vec<String>) {
    let path = root.join("docs/architecture-interface.txt");
    let Ok(text) = fs::read_to_string(&path) else {
        errors.push(format!("missing interface baseline: {}", path.display()));
        return;
    };
    let expected: BTreeSet<&str> = text
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect();
    let current: BTreeSet<&str> = current.iter().map(String::as_str).collect();
    for item in expected.difference(&current) {
        errors.push(format!(
            "public interface removed or changed without contract update: {item}"
        ));
    }
    for item in current.difference(&expected) {
        errors.push(format!(
            "public interface expanded without contract update: {item}"
        ));
    }
}

#[derive(Default)]
struct PatternVisitor {
    static_mut: Vec<usize>,
    dense_eight_ranges: Vec<usize>,
    unfinished: Vec<usize>,
}

impl<'ast> Visit<'ast> for PatternVisitor {
    fn visit_item_static(&mut self, item: &'ast ItemStatic) {
        if matches!(item.mutability, syn::StaticMutability::Mut(_)) {
            self.static_mut.push(item.static_token.span.start().line);
        }
        syn::visit::visit_item_static(self, item);
    }

    fn visit_expr_range(&mut self, range: &'ast ExprRange) {
        let integer = |expression: &Option<Box<Expr>>, expected: u64| {
            expression.as_deref().is_some_and(|expression| {
                matches!(expression, Expr::Lit(ExprLit { lit: Lit::Int(value), .. }) if value.base10_parse::<u64>().is_ok_and(|value| value == expected))
            })
        };
        if integer(&range.start, 0) && integer(&range.end, 8) {
            self.dense_eight_ranges
                .push(range.limits.span().start().line);
        }
        syn::visit::visit_expr_range(self, range);
    }

    fn visit_macro(&mut self, node: &'ast Macro) {
        if node.path.segments.last().is_some_and(|segment| {
            matches!(segment.ident.to_string().as_str(), "todo" | "unimplemented")
        }) {
            self.unfinished.push(node.path.span().start().line);
        }
        syn::visit::visit_macro(self, node);
    }
}

fn check_source_patterns(root: &Path, sources: &[SourceFile], errors: &mut Vec<String>) {
    let banned_text = [
        ("MAX_CORES", "fixed CPU capacity"),
        ("start_all_cores", "firmware-driven secondary startup"),
        ("STDOUT_FILENO", "stdout syscall side path"),
    ];
    for source in sources {
        for (needle, label) in banned_text {
            if source.text.contains(needle) {
                errors.push(format!(
                    "{}: banned pattern reintroduces {label}",
                    source.relative
                ));
            }
        }
        let lowercase = source.text.to_ascii_lowercase();
        if lowercase.contains("read-only ext2")
            || lowercase.contains("read_only ext2")
            || source.text.contains("只读 ext2")
        {
            errors.push(format!(
                "{}: banned pattern reintroduces read-only filesystem dual track",
                source.relative
            ));
        }
        let mut visitor = PatternVisitor::default();
        visitor.visit_file(&source.syntax);
        for line in visitor.static_mut {
            errors.push(format!(
                "{}: static mut global state is forbidden",
                source.at(line)
            ));
        }
        for line in visitor.dense_eight_ranges {
            errors.push(format!(
                "{}: dense eight-hart iteration is forbidden",
                source.at(line)
            ));
        }
        for line in visitor.unfinished {
            errors.push(format!(
                "{}: unfinished executable path is forbidden",
                source.at(line)
            ));
        }
    }

    let garbage = [
        "common", "utils", "helpers", "misc", "manager", "base", "shared", "core",
    ];
    for domain in SOURCE_DOMAINS {
        collect_garbage_directories(&root.join(domain.root), root, &garbage, errors);
    }
}

fn collect_garbage_directories(
    directory: &Path,
    root: &Path,
    garbage: &[&str],
    errors: &mut Vec<String>,
) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| garbage.contains(&name))
        {
            errors.push(format!(
                "{}: directory name has no domain meaning",
                path.strip_prefix(root).unwrap_or(&path).display()
            ));
        }
        collect_garbage_directories(&path, root, garbage, errors);
    }
}

#[derive(Default)]
struct GlobalVisitor {
    lines: Vec<usize>,
}

impl<'ast> Visit<'ast> for GlobalVisitor {
    fn visit_item_static(&mut self, item: &'ast ItemStatic) {
        self.lines.push(item.static_token.span.start().line);
    }
}

fn check_global_owners(sources: &[SourceFile], errors: &mut Vec<String>) {
    for source in sources.iter().filter(|source| source.binary_crate) {
        let mut visitor = GlobalVisitor::default();
        visitor.visit_file(&source.syntax);
        for (index, line) in source.lines.iter().enumerate() {
            if line.contains("static ref ") {
                visitor.lines.push(index + 1);
            }
        }
        visitor.lines.sort_unstable();
        visitor.lines.dedup();
        for line in visitor.lines {
            if !source.preceding_contains(line, 4, "OWNER:") {
                errors.push(format!(
                    "{}: global state lacks an OWNER declaration",
                    source.at(line)
                ));
            }
        }
    }
}

#[derive(Default)]
struct UnsafeVisitor {
    lines: Vec<usize>,
}

impl UnsafeVisitor {
    fn signature(&mut self, signature: &Signature) {
        if let Some(unsafety) = signature.unsafety {
            self.lines.push(unsafety.span.start().line);
        }
    }
}

impl<'ast> Visit<'ast> for UnsafeVisitor {
    fn visit_expr_unsafe(&mut self, expression: &'ast syn::ExprUnsafe) {
        self.lines.push(expression.unsafe_token.span.start().line);
        syn::visit::visit_expr_unsafe(self, expression);
    }

    fn visit_item_impl(&mut self, item: &'ast ItemImpl) {
        if let Some(unsafety) = item.unsafety {
            self.lines.push(unsafety.span.start().line);
        }
        syn::visit::visit_item_impl(self, item);
    }

    fn visit_item_fn(&mut self, item: &'ast ItemFn) {
        self.signature(&item.sig);
        syn::visit::visit_item_fn(self, item);
    }

    fn visit_impl_item_fn(&mut self, item: &'ast ImplItemFn) {
        self.signature(&item.sig);
        syn::visit::visit_impl_item_fn(self, item);
    }

    fn visit_foreign_item_fn(&mut self, item: &'ast ForeignItemFn) {
        self.signature(&item.sig);
        syn::visit::visit_foreign_item_fn(self, item);
    }

    fn visit_item_foreign_mod(&mut self, item: &'ast ItemForeignMod) {
        self.lines.push(item.abi.extern_token.span.start().line);
        syn::visit::visit_item_foreign_mod(self, item);
    }
}

fn check_unsafe_proofs(sources: &[SourceFile], errors: &mut Vec<String>) {
    for source in sources {
        let mut visitor = UnsafeVisitor::default();
        visitor.visit_file(&source.syntax);
        visitor.lines.sort_unstable();
        visitor.lines.dedup();
        for line in visitor.lines {
            if !source.preceding_contains(line, 6, "SAFETY:") {
                errors.push(format!(
                    "{}: unsafe operation lacks a local SAFETY proof",
                    source.at(line)
                ));
            }
        }
    }
}

fn syscall_constants(file: &File) -> BTreeSet<String> {
    file.items
        .iter()
        .filter_map(|item| match item {
            syn::Item::Const(item) if item.ident.to_string().starts_with("SYSCALL_") => {
                Some(item.ident.to_string())
            }
            _ => None,
        })
        .collect()
}

#[derive(Default)]
struct DispatchVisitor {
    constants: BTreeSet<String>,
    numeric_arms: Vec<usize>,
}

impl<'ast> Visit<'ast> for DispatchVisitor {
    fn visit_path(&mut self, path: &'ast SynPath) {
        for segment in &path.segments {
            let name = segment.ident.to_string();
            if name.starts_with("SYSCALL_") {
                self.constants.insert(name);
            }
        }
        syn::visit::visit_path(self, path);
    }

    fn visit_arm(&mut self, arm: &'ast Arm) {
        if matches!(
            &arm.pat,
            Pat::Lit(ExprLit {
                lit: Lit::Int(_),
                ..
            })
        ) {
            self.numeric_arms
                .push(arm.fat_arrow_token.spans[0].start().line);
        }
        syn::visit::visit_arm(self, arm);
    }

    fn visit_pat_ident(&mut self, pattern: &'ast PatIdent) {
        let name = pattern.ident.to_string();
        if name.starts_with("SYSCALL_") {
            self.constants.insert(name);
        }
        syn::visit::visit_pat_ident(self, pattern);
    }

    fn visit_expr_match(&mut self, node: &'ast ExprMatch) {
        syn::visit::visit_expr_match(self, node);
    }
}

fn check_abi(root: &Path, errors: &mut Vec<String>) {
    let abi_path = root.join("syscall-abi/src/lib.rs");
    let dispatch_path = root.join("kernel/src/syscall/mod.rs");
    let abi_text = fs::read_to_string(&abi_path).expect("syscall ABI source must exist");
    let dispatch_text = fs::read_to_string(&dispatch_path).expect("syscall dispatch must exist");
    let abi = syn::parse_file(&abi_text).expect("syscall ABI must parse");
    let dispatch = syn::parse_file(&dispatch_text).expect("syscall dispatch must parse");
    let constants = syscall_constants(&abi);
    let mut visitor = DispatchVisitor::default();
    visitor.visit_file(&dispatch);
    for name in constants.difference(&visitor.constants) {
        errors.push(format!("syscall ABI constant is not dispatched: {name}"));
    }
    for name in visitor.constants.difference(&constants) {
        errors.push(format!(
            "dispatcher uses a syscall absent from syscall-abi: {name}"
        ));
    }
    for line in visitor.numeric_arms {
        errors.push(format!(
            "kernel/src/syscall/mod.rs:{line}: raw numeric syscall dispatch is forbidden"
        ));
    }
}

fn check_documentation(root: &Path, errors: &mut Vec<String>) {
    let abi_text = fs::read_to_string(root.join("syscall-abi/src/lib.rs")).unwrap();
    let abi = syn::parse_file(&abi_text).unwrap();
    let count = syscall_constants(&abi).len();
    let readme = fs::read_to_string(root.join("README.md")).unwrap();
    if !readme.contains(&format!("{count} 个 Linux/riscv64 syscall")) {
        errors.push(format!(
            "README syscall count must match syscall-abi ({count})"
        ));
    }
    let agents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
    for phrase in [
        "个 Linux/riscv64 syscall",
        "同步读写 ext2",
        "nightly-",
        "三个组件",
    ] {
        if agents.contains(phrase) {
            errors.push(format!(
                "AGENTS.md duplicates discoverable project state: {phrase}"
            ));
        }
    }
    let architecture = fs::read_to_string(root.join("docs/architecture.md")).unwrap();
    for phrase in [
        "startup stack、processor slot",
        "- fd/OFD、普通文件 I/O",
        "- writable filesystem",
        "**fd/OFD 文件竖切**",
    ] {
        if architecture.contains(phrase) {
            errors.push(format!(
                "docs/architecture.md retains superseded current-state claim: {phrase}"
            ));
        }
    }
}
