// Generated by scripts/generate_icon_font.py; do not edit by hand.
export const SYSTEM_ICON_FAMILY = "liteos-icons";

export const SYSTEM_ICON_GLYPHS = {
  "chevron-right": "\uE000",
  "chevron-down": "\uE001",
  "sort-up": "\uE002",
  "sort-down": "\uE003",
  "playing": "\uE004",
  "check": "\uE005",
  "search": "\uE006",
} as const;

export type SystemIconName = keyof typeof SYSTEM_ICON_GLYPHS;
