#!/usr/bin/env python3
"""从 root tree 生成带逐文件 checksum 与 RSA256 signature 的 APK v2 package。"""

from __future__ import annotations

import gzip
import hashlib
import io
import os
import subprocess
import tarfile
import tempfile
import zlib
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ApkPackageMetadata:
    """@description APK v2 control metadata 的受控输入。"""

    name: str
    version: str
    description: str
    url: str
    license: str
    arch: str
    provides: tuple[str, ...] = ()
    dependencies: tuple[str, ...] = ()


def _gzip(payload: bytes) -> bytes:
    """生成不携带 host filename/time 的确定性 gzip member。"""
    output = io.BytesIO()
    with gzip.GzipFile(fileobj=output, mode="wb", filename="", mtime=0, compresslevel=9) as stream:
        stream.write(payload)
    return output.getvalue()


def _cut_tar(payload: bytes) -> bytes:
    """删除 tar EOF record，使 APK 的连续 gzip members 能被同一 archive reader 消费。"""
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:") as archive:
        end = 0
        for member in archive.getmembers():
            data_blocks = (member.size + 511) // 512
            end = max(end, member.offset_data + data_blocks * 512)
    if end == 0 or end % 512 != 0:
        raise RuntimeError("failed to determine APK tar payload boundary")
    return payload[:end]


def _tar_info(path: Path, relative: str, hardlink: str | None) -> tarfile.TarInfo:
    """把 host entry 映射为 root-owned、时间归零的 package entry。"""
    stat = path.lstat()
    name = relative.rstrip("/")
    if path.is_symlink():
        target = os.readlink(path)
        info = tarfile.TarInfo(name)
        info.type = tarfile.SYMTYPE
        info.linkname = target
        info.pax_headers = {
            "APK-TOOLS.checksum.SHA1": hashlib.sha1(target.encode()).hexdigest()
        }
    elif path.is_dir():
        info = tarfile.TarInfo(f"{name}/")
        info.type = tarfile.DIRTYPE
    elif hardlink is not None:
        info = tarfile.TarInfo(name)
        info.type = tarfile.LNKTYPE
        info.linkname = hardlink
    elif path.is_file():
        info = tarfile.TarInfo(name)
        info.type = tarfile.REGTYPE
        info.size = stat.st_size
        info.pax_headers = {
            "APK-TOOLS.checksum.SHA1": hashlib.sha1(path.read_bytes()).hexdigest()
        }
    else:
        raise RuntimeError(f"unsupported APK staging entry: {path}")
    info.mode = stat.st_mode & 0o7777
    info.uid = 0
    info.gid = 0
    info.uname = "root"
    info.gname = "root"
    info.mtime = 0
    return info


def _data_member(root: Path) -> tuple[bytes, int]:
    """构造 data.tar.gz，并保留 hardlink identity 与逐文件 SHA-1。"""
    output = io.BytesIO()
    hardlinks: dict[tuple[int, int], str] = {}
    unique_size = 0
    with tarfile.open(fileobj=output, mode="w", format=tarfile.PAX_FORMAT) as archive:
        for path in sorted(root.rglob("*"), key=lambda entry: entry.relative_to(root).as_posix()):
            relative = path.relative_to(root).as_posix()
            stat = path.lstat()
            inode = (stat.st_dev, stat.st_ino)
            hardlink = None
            if path.is_file() and not path.is_symlink():
                hardlink = hardlinks.get(inode)
                if hardlink is None:
                    hardlinks[inode] = relative
                    unique_size += stat.st_size
            info = _tar_info(path, relative, hardlink)
            source = path.open("rb") if info.isreg() else None
            try:
                archive.addfile(info, source)
            finally:
                if source is not None:
                    source.close()
    return _gzip(_cut_tar(output.getvalue())), max(unique_size, 1)


def _control_member(metadata: ApkPackageMetadata, installed_size: int, datahash: str) -> bytes:
    """生成最小且完整的 .PKGINFO control member。"""
    lines = (
        "# Generated by LiteOS apk_package.py",
        f"pkgname = {metadata.name}",
        f"pkgver = {metadata.version}",
        f"pkgdesc = {metadata.description}",
        f"url = {metadata.url}",
        "builddate = 0",
        "packager = LiteOS local repository",
        f"size = {installed_size}",
        f"arch = {metadata.arch}",
        f"origin = {metadata.name}",
        f"license = {metadata.license}",
        *(f"depend = {dependency}" for dependency in metadata.dependencies),
        *(f"provides = {provided}" for provided in metadata.provides),
        f"datahash = {datahash}",
    )
    content = ("\n".join(lines) + "\n").encode()
    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode="w", format=tarfile.PAX_FORMAT) as archive:
        info = tarfile.TarInfo(".PKGINFO")
        info.size = len(content)
        info.mode = 0o644
        info.uid = 0
        info.gid = 0
        info.uname = "root"
        info.gname = "root"
        info.mtime = 0
        archive.addfile(info, io.BytesIO(content))
    return _gzip(_cut_tar(output.getvalue()))


def _signature_member(control: bytes, private_key: Path, public_key: Path) -> bytes:
    """按 apk-tools RSA256 contract 签名压缩后的完整 control member。"""
    with tempfile.TemporaryDirectory(prefix="liteos-apk-sign-") as directory:
        control_path = Path(directory) / "control.tar.gz"
        signature_path = Path(directory) / "signature"
        control_path.write_bytes(control)
        result = subprocess.run(
            [
                "openssl",
                "dgst",
                "-sha256",
                "-sign",
                str(private_key),
                "-out",
                str(signature_path),
                str(control_path),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"failed to sign APK control member: {result.stdout}")
        signature = signature_path.read_bytes()
    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode="w", format=tarfile.PAX_FORMAT) as archive:
        info = tarfile.TarInfo(f".SIGN.RSA256.{public_key.name}")
        info.size = len(signature)
        info.mode = 0o644
        info.uid = 0
        info.gid = 0
        info.uname = "root"
        info.gname = "root"
        info.mtime = 0
        archive.addfile(info, io.BytesIO(signature))
    return _gzip(_cut_tar(output.getvalue()))


def build_signed_apk(
    root: Path,
    output: Path,
    metadata: ApkPackageMetadata,
    private_key: Path,
    public_key: Path,
) -> Path:
    """生成 signature + control + data 三成员 APK v2 package。"""
    if not root.is_dir():
        raise RuntimeError(f"APK staging root does not exist: {root}")
    data, installed_size = _data_member(root)
    control = _control_member(metadata, installed_size, hashlib.sha256(data).hexdigest())
    signature = _signature_member(control, private_key, public_key)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(".tmp")
    temporary.write_bytes(signature + control + data)
    os.replace(temporary, output)
    return output


def tamper_signed_apk_control(source: Path, output: Path) -> Path:
    """保持 gzip/tar 有效但修改已签名 control bytes，用于验证 RSA 拒绝路径。"""
    remaining = source.read_bytes()
    members: list[bytes] = []
    while remaining:
        decoder = zlib.decompressobj(16 + zlib.MAX_WBITS)
        decoder.decompress(remaining)
        decoder.flush()
        consumed = len(remaining) - len(decoder.unused_data)
        if consumed == 0:
            raise RuntimeError(f"failed to split APK gzip members: {source}")
        members.append(remaining[:consumed])
        remaining = decoder.unused_data
    if len(members) != 3:
        raise RuntimeError(f"expected three APK v2 members: {source}")
    control = bytearray(gzip.decompress(members[1]))
    marker = b"pkgdesc = "
    position = control.find(marker)
    if position < 0 or position + len(marker) >= len(control):
        raise RuntimeError(f"APK control lacks pkgdesc: {source}")
    position += len(marker)
    control[position] ^= 1
    output.write_bytes(members[0] + _gzip(bytes(control)) + members[2])
    return output
