#!/usr/bin/env python3
"""Generate and control LiteOS's single macOS UTM GUI runtime."""

from __future__ import annotations

import os
import plistlib
import shutil
import subprocess
import time
from pathlib import Path

UTM_APP = Path("/Applications/UTM.app")
UTM_VERSION = "4.7.5"
UTMCTL = UTM_APP / "Contents/MacOS/utmctl"
UTM_INFO = UTM_APP / "Contents/Info.plist"
UTM_DOCUMENTS = Path.home() / "Library/Containers/com.utmapp.UTM/Data/Documents"
UTM_ARTIFACTS = (
    Path.home()
    / "Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/LiteOS"
)
VM_NAME = "LiteOS"
VM_UUID = "11E05A11-7E05-4A11-8E7A-11E05A110001"
VM_PACKAGE = UTM_ARTIFACTS / f"{VM_NAME}.utm"
VM_DOCUMENT_PACKAGE = UTM_DOCUMENTS / f"{VM_NAME}.utm"


def _installed_version() -> str:
    if not UTM_INFO.is_file() or not UTMCTL.is_file():
        raise RuntimeError(
            f"UTM {UTM_VERSION} is required at {UTM_APP}; "
            "install the pinned release from https://github.com/utmapp/UTM/releases/tag/v4.7.5"
        )
    with UTM_INFO.open("rb") as stream:
        value = plistlib.load(stream).get("CFBundleShortVersionString")
    if value != UTM_VERSION:
        raise RuntimeError(
            f"UTM {UTM_VERSION} is required; {UTM_APP} contains {value or 'an unknown version'}"
        )
    return value


def _memory_mib(value: str) -> int:
    normalized = value.strip().upper()
    factors = {"M": 1, "G": 1024}
    if len(normalized) < 2 or normalized[-1] not in factors:
        raise ValueError(f"UTM memory must use M or G units; got {value!r}")
    amount = int(normalized[:-1])
    if amount <= 0:
        raise ValueError("UTM memory must be positive")
    return amount * factors[normalized[-1]]


def _publish_file(source: Path, destination: Path) -> None:
    """Publish one artifact as a hard link so UTM and workflow share one inode."""
    source = source.resolve(strict=True)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        source_stat = source.stat()
        destination_stat = destination.stat()
        if (source_stat.st_dev, source_stat.st_ino) == (
            destination_stat.st_dev,
            destination_stat.st_ino,
        ):
            return
        destination.unlink()
    try:
        os.link(source, destination)
    except OSError as error:
        raise RuntimeError(
            f"UTM artifact publication requires one APFS volume: {source} -> {destination}"
        ) from error


def _qemu_path(path: Path) -> str:
    """Encode a host path for QEMU's comma-separated key/value parser."""
    return str(path).replace(",", ",,")


def _configuration(
    *,
    memory_mib: int,
    cpu_count: int,
    kernel: Path | None = None,
    rootfs: Path | None = None,
) -> dict[str, object]:
    kernel = kernel or UTM_ARTIFACTS / "kernel"
    rootfs = rootfs or UTM_ARTIFACTS / "rootfs.img"
    additional = [
        "-global",
        "virtio-mmio.force-legacy=false",
        "-global",
        "virtio-gpu-device.xres=3008",
        "-global",
        "virtio-gpu-device.yres=1692",
        "-rtc",
        "base=utc",
        "-drive",
        '"'
        + (
            "if=none,media=disk,id=driverootfs,format=raw,"
            f"file.filename={_qemu_path(rootfs)},discard=unmap,detect-zeroes=unmap"
        )
        + '"',
        "-kernel",
        f'"{kernel}"',
        "-device",
        "virtio-blk-device,drive=driverootfs",
        "-object",
        "rng-random,filename=/dev/urandom,id=rng0",
        "-device",
        "virtio-rng-device,rng=rng0",
        "-device",
        "virtio-keyboard-device",
        "-device",
        "virtio-tablet-device",
        "-device",
        "virtio-sound-device,audiodev=audio0,streams=1",
    ]
    return {
        "Backend": "QEMU",
        "ConfigurationVersion": 4,
        "Information": {
            "Name": VM_NAME,
            "Icon": "linux",
            "IconCustom": False,
            "Notes": "Generated by LiteOS; edit scripts/utm_runtime.py, not this VM.",
            "UUID": VM_UUID,
        },
        "System": {
            "Architecture": "aarch64",
            "Target": "virt",
            "CPU": "host",
            "CPUFlagsAdd": [],
            "CPUFlagsRemove": [],
            "CPUCount": cpu_count,
            "ForceMulticore": False,
            "MemorySize": memory_mib,
            "JITCacheSize": 0,
        },
        "QEMU": {
            "DebugLog": True,
            "UEFIBoot": False,
            "RNGDevice": False,
            "BalloonDevice": False,
            "TPMDevice": False,
            "Hypervisor": True,
            "TSO": False,
            "RTCLocalTime": False,
            "PS2Controller": False,
            "MachinePropertyOverride": (
                "gic-version=3,its=off,secure=off,virtualization=off,acpi=off,"
                "highmem-ecam=off"
            ),
            "AdditionalArguments": additional,
        },
        "Input": {
            "UsbBusSupport": "Disabled",
            "UsbSharing": False,
            "MaximumUsbShare": 0,
        },
        "Sharing": {
            "DirectoryShareMode": "None",
            "DirectoryShareReadOnly": False,
            "ClipboardSharing": True,
        },
        "Display": [
            {
                "Hardware": "virtio-gpu-gl-device",
                "DynamicResolution": True,
                "UpscalingFilter": "Linear",
                "DownscalingFilter": "Linear",
                "NativeResolution": True,
            }
        ],
        "Drive": [],
        "Network": [
            {
                "Mode": "Emulated",
                "Hardware": "virtio-net-device",
                "MacAddress": "02:4C:49:54:45:01",
                "IsolateFromHost": False,
                "PortForward": [],
            }
        ],
        "Serial": [
            {
                "Mode": "Ptty",
                "Target": "Auto",
            }
        ],
        "Sound": [],
    }


def prepare(
    *,
    kernel: Path,
    rootfs: Path,
    memory: str,
    cpu_count: int,
) -> Path:
    """Publish current artifacts and an exact UTM v4 configuration."""
    _installed_version()
    if cpu_count <= 0:
        raise ValueError("UTM CPU count must be positive")
    UTM_ARTIFACTS.mkdir(parents=True, exist_ok=True)
    published_rootfs = UTM_ARTIFACTS / "rootfs.img"
    published_kernel = UTM_ARTIFACTS / "kernel"
    _publish_file(rootfs, published_rootfs)
    _publish_file(kernel, published_kernel)
    VM_PACKAGE.mkdir(parents=True, exist_ok=True)
    config = _configuration(
        memory_mib=_memory_mib(memory),
        cpu_count=cpu_count,
        kernel=published_kernel,
        rootfs=published_rootfs,
    )
    with (VM_PACKAGE / "config.plist").open("wb") as stream:
        plistlib.dump(config, stream, fmt=plistlib.FMT_XML, sort_keys=False)
        stream.flush()
        os.fsync(stream.fileno())
    return VM_PACKAGE


def _ctl(*arguments: str) -> str:
    try:
        result = subprocess.run(
            [str(UTMCTL), *arguments],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=30,
        )
    except subprocess.TimeoutExpired as error:
        raise RuntimeError(f"utmctl {' '.join(arguments)} did not complete") from error
    return result.stdout.strip()


def _registered() -> bool:
    return _status() is not None


def _status() -> str | None:
    """Return status from one registry snapshot without querying a stale VM handle."""
    for line in _ctl("list").splitlines()[1:]:
        fields = line.split(maxsplit=2)
        if len(fields) == 3 and fields[0] == VM_UUID:
            return fields[1]
    return None


def _apple_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _start_visible() -> None:
    """Start through UTM's public scripting API so the Metal display window is owned by UTM."""
    script = (
        'tell application id "com.utmapp.UTM"\n'
        f'  set vm to first virtual machine whose id is "{VM_UUID}"\n'
        "  start vm\n"
        "end tell"
    )
    try:
        subprocess.run(
            ["osascript", "-e", script],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=30,
        )
    except subprocess.TimeoutExpired as error:
        raise RuntimeError("UTM did not create the LiteOS display window") from error


def _ensure_registered() -> None:
    subprocess.run(["open", "-a", str(UTM_APP)], check=True)
    for _ in range(40):
        try:
            if _registered():
                return
            break
        except (subprocess.CalledProcessError, RuntimeError):
            time.sleep(0.25)
    else:
        raise RuntimeError("UTM did not become available for managed VM registration")
    package = _apple_string(str(VM_PACKAGE))
    script = (
        'tell application id "com.utmapp.UTM"\n'
        f'  import new virtual machine from POSIX file "{package}"\n'
        "end tell"
    )
    subprocess.run(
        ["osascript", "-e", script],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=30,
    )
    for _ in range(40):
        if _registered():
            return
        time.sleep(0.25)
    raise RuntimeError(f"UTM did not register generated VM at {VM_PACKAGE}")


def _remove_registered() -> None:
    """Remove only the generated VM registration before publishing its next config."""
    subprocess.run(["open", "-a", str(UTM_APP)], check=True)
    for _ in range(40):
        try:
            status = _status()
            if status is None:
                if VM_DOCUMENT_PACKAGE.exists():
                    shutil.rmtree(VM_DOCUMENT_PACKAGE)
                return
            if status != "stopped":
                raise RuntimeError(
                    f"UTM VM {VM_NAME!r} must be stopped before regeneration; status={status}"
                )
            _ctl("delete", VM_UUID)
            if VM_DOCUMENT_PACKAGE.exists():
                shutil.rmtree(VM_DOCUMENT_PACKAGE)
            return
        except subprocess.CalledProcessError:
            time.sleep(0.25)
    raise RuntimeError("UTM did not become available for managed VM regeneration")


def run_gui(
    *,
    kernel: Path,
    rootfs: Path,
    memory: str,
    cpu_count: int,
) -> None:
    """Start the generated VM and keep the invoking terminal as lifecycle owner."""
    _installed_version()
    _remove_registered()
    prepare(kernel=kernel, rootfs=rootfs, memory=memory, cpu_count=cpu_count)
    _ensure_registered()
    status = _status()
    if status != "stopped":
        raise RuntimeError(f"UTM VM {VM_NAME!r} must be stopped before launch; status={status}")
    _start_visible()
    for _ in range(40):
        status = _status()
        if status is None:
            raise RuntimeError("UTM removed the managed LiteOS registration during launch")
        if status == "started":
            break
        time.sleep(0.25)
    else:
        raise RuntimeError(f"UTM failed to start {VM_NAME}")
    try:
        while True:
            status = _status()
            if status == "stopped":
                return
            if status is None:
                raise RuntimeError("UTM removed the managed LiteOS registration while running")
            time.sleep(0.5)
    except KeyboardInterrupt:
        if _registered():
            _ctl("stop", VM_UUID)
        return
