use std::{collections::BTreeSet, fs, path::Path};

use proc_macro2::Span;
use syn::{
    Field, ForeignItemFn, ImplItemFn, ItemConst, ItemEnum, ItemFn, ItemImpl, ItemMod, ItemStatic,
    ItemStruct, ItemTrait, ItemType, ItemUnion, ItemUse, Signature, TraitItem, Visibility,
    visit::Visit,
};

use super::super::{SourceFile, normalized};

const INTERFACE_HEADER: &str = "# Generated only by cargo run -p architecture-check -- --write-interface\n\
# Do not edit this file manually.\n\
# Any change is an architecture interface change and must be reviewed.\n";
const INTERFACE_BASELINE: &str = "docs/generated/architecture-interface.txt";

fn is_scoped_visible(visibility: &Visibility) -> bool {
    matches!(visibility, Visibility::Restricted(restricted) if !restricted.path.is_ident("self"))
}

fn is_bare_public(visibility: &Visibility) -> bool {
    matches!(visibility, Visibility::Public(_))
}

fn cfg_test_only(attributes: &[syn::Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        attribute.path().is_ident("cfg")
            && attribute
                .parse_args::<syn::Ident>()
                .is_ok_and(|condition| condition == "test")
    })
}

struct SurfaceCollector<'a> {
    relative: &'a str,
    entries: Vec<String>,
    errors: Option<&'a mut Vec<String>>,
    binary_crate: bool,
    owner: Vec<String>,
}

impl SurfaceCollector<'_> {
    fn record(&mut self, declaration: String) {
        self.entries
            .push(format!("{} :: {}", self.relative, declaration.trim()));
    }

    fn visibility(&mut self, visibility: &Visibility, span: Span, declaration: String) -> bool {
        if self.binary_crate
            && is_bare_public(visibility)
            && let Some(errors) = self.errors.as_deref_mut()
        {
            errors.push(format!(
                "{}:{}: binary-crate implementation must use scoped visibility",
                self.relative,
                span.start().line
            ));
        }
        if is_scoped_visible(visibility) {
            self.record(format!("{} {declaration}", normalized(visibility)));
            true
        } else {
            false
        }
    }

    fn owner_name(&self) -> String {
        self.owner.join("::")
    }

    fn signature(&mut self, visibility: &Visibility, signature: &Signature, span: Span) {
        let owner = self.owner_name();
        let signature = normalized(signature);
        let declaration = if owner.is_empty() {
            signature
        } else {
            format!("impl {owner} :: {signature}")
        };
        self.visibility(visibility, span, declaration);
    }
}

impl<'ast> Visit<'ast> for SurfaceCollector<'_> {
    fn visit_item_fn(&mut self, item: &'ast ItemFn) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }

    fn visit_item_struct(&mut self, item: &'ast ItemStruct) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        let name = item.ident.to_string();
        let declaration = format!("struct {} {}", item.ident, normalized(&item.generics));
        self.visibility(&item.vis, item.ident.span(), declaration);
        self.owner.push(name);
        for field in &item.fields {
            self.visit_field(field);
        }
        self.owner.pop();
    }

    fn visit_item_union(&mut self, item: &'ast ItemUnion) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        let declaration = format!("union {}", item.ident);
        self.visibility(&item.vis, item.ident.span(), declaration);
        self.owner.push(item.ident.to_string());
        for field in &item.fields.named {
            self.visit_field(field);
        }
        self.owner.pop();
    }

    fn visit_field(&mut self, field: &'ast Field) {
        if cfg_test_only(&field.attrs) {
            return;
        }
        let name = field
            .ident
            .as_ref()
            .map_or_else(|| "<tuple>".to_owned(), ToString::to_string);
        let owner = self.owner_name();
        let ty = normalized(&field.ty);
        self.visibility(
            &field.vis,
            field
                .ident
                .as_ref()
                .map_or_else(Span::call_site, |id| id.span()),
            format!("{owner} :: {name} : {ty}"),
        );
    }

    fn visit_item_enum(&mut self, item: &'ast ItemEnum) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        if self.visibility(
            &item.vis,
            item.ident.span(),
            format!("enum {} {}", item.ident, normalized(&item.generics)),
        ) {
            for variant in &item.variants {
                self.record(format!("enum {} :: {}", item.ident, normalized(variant)));
            }
        }
    }

    fn visit_item_trait(&mut self, item: &'ast ItemTrait) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        if self.visibility(
            &item.vis,
            item.ident.span(),
            format!("trait {} {}", item.ident, normalized(&item.generics)),
        ) {
            for trait_item in &item.items {
                let declaration = match trait_item {
                    TraitItem::Fn(function) => normalized(&function.sig),
                    TraitItem::Const(constant) => {
                        format!("const {} : {}", constant.ident, normalized(&constant.ty))
                    }
                    TraitItem::Type(ty) => {
                        format!("type {} {}", ty.ident, normalized(&ty.generics))
                    }
                    other => normalized(other),
                };
                self.record(format!("trait {} :: {declaration}", item.ident));
            }
        }
    }

    fn visit_item_impl(&mut self, item: &'ast ItemImpl) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        self.owner.push(normalized(&item.self_ty));
        syn::visit::visit_item_impl(self, item);
        self.owner.pop();
    }

    fn visit_impl_item_fn(&mut self, item: &'ast ImplItemFn) {
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }

    fn visit_item_const(&mut self, item: &'ast ItemConst) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        let declaration = format!(
            "const {} : {} = {}",
            item.ident,
            normalized(&item.ty),
            normalized(&item.expr)
        );
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_static(&mut self, item: &'ast ItemStatic) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        let declaration = format!("static {} : {}", item.ident, normalized(&item.ty));
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_type(&mut self, item: &'ast ItemType) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        let declaration = format!(
            "type {} {} = {}",
            item.ident,
            normalized(&item.generics),
            normalized(&item.ty)
        );
        self.visibility(&item.vis, item.ident.span(), declaration);
    }

    fn visit_item_mod(&mut self, item: &'ast ItemMod) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        self.visibility(&item.vis, item.ident.span(), format!("mod {}", item.ident));
        syn::visit::visit_item_mod(self, item);
    }

    fn visit_item_use(&mut self, item: &'ast ItemUse) {
        if cfg_test_only(&item.attrs) {
            return;
        }
        self.visibility(
            &item.vis,
            item.use_token.span,
            format!("use {}", normalized(&item.tree)),
        );
    }

    fn visit_foreign_item_fn(&mut self, item: &'ast ForeignItemFn) {
        self.signature(&item.vis, &item.sig, item.sig.ident.span());
    }
}

fn interface_surface(sources: &[SourceFile]) -> Vec<String> {
    let mut surface = Vec::new();
    for source in sources.iter().filter(|source| source.binary_crate) {
        let mut collector = SurfaceCollector {
            relative: &source.relative,
            entries: Vec::new(),
            errors: None,
            binary_crate: source.binary_crate,
            owner: Vec::new(),
        };
        collector.visit_file(&source.syntax);
        surface.extend(collector.entries);
    }
    surface.sort();
    surface.dedup();
    surface
}

fn check_visibility(sources: &[SourceFile], errors: &mut Vec<String>) {
    for source in sources.iter().filter(|source| source.binary_crate) {
        let mut collector = SurfaceCollector {
            relative: &source.relative,
            entries: Vec::new(),
            errors: Some(errors),
            binary_crate: source.binary_crate,
            owner: Vec::new(),
        };
        collector.visit_file(&source.syntax);
    }
}

fn check_interface_baseline(root: &Path, current: &[String], errors: &mut Vec<String>) {
    let path = root.join(INTERFACE_BASELINE);
    let Ok(text) = fs::read_to_string(&path) else {
        errors.push(format!("missing interface baseline: {}", path.display()));
        return;
    };
    if !text.starts_with(INTERFACE_HEADER) {
        errors.push(format!(
            "{}: generated header is stale; regenerate it through architecture-check",
            path.display()
        ));
    }
    let expected: BTreeSet<&str> = text
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect();
    let current: BTreeSet<&str> = current.iter().map(String::as_str).collect();
    for item in expected.difference(&current) {
        errors.push(format!(
            "public interface removed or changed without contract update: {item}"
        ));
    }
    for item in current.difference(&expected) {
        errors.push(format!(
            "public interface expanded without contract update: {item}"
        ));
    }
}

/// 校验 scoped visibility，并校验或生成其唯一 interface baseline。
///
/// `root` 定位基线，`sources` 提供已解析语法树；`write_interface` 选择生成模式，
/// 所有 visibility、baseline 和写入失败都追加到 `errors`。
pub(super) fn check(
    root: &Path,
    sources: &[SourceFile],
    write_interface: bool,
    errors: &mut Vec<String>,
) {
    check_visibility(sources, errors);
    let surface = interface_surface(sources);
    if write_interface {
        if errors.is_empty() {
            let baseline = root.join(INTERFACE_BASELINE);
            let content = format!("{INTERFACE_HEADER}{}\n", surface.join("\n"));
            if let Err(error) = fs::write(&baseline, content) {
                errors.push(format!("failed to write {}: {error}", baseline.display()));
            }
        }
    } else {
        check_interface_baseline(root, &surface, errors);
    }
}

#[cfg(test)]
pub(super) fn production_surface(sources: &[SourceFile]) -> Vec<String> {
    interface_surface(sources)
}
